'use client';

import { useEffect, useRef } from 'react';
import type { HeatmapData } from '@/lib/clarity/postprocess';

interface ContrastViewerProps {
  imageUrl?: string | null;
  heatmap?: HeatmapData;
  /** Omit outer card chrome for embedding inside a scan frame. */
  embedded?: boolean;
}

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

function heatToRgba(value: number): [number, number, number, number] {
  const x = clamp01(value);

  const r = clamp01(1.5 - Math.abs(4 * x - 3));
  const g = clamp01(1.5 - Math.abs(4 * x - 2));
  const b = clamp01(1.5 - Math.abs(4 * x - 1));
  const alpha = clamp01(x * 0.72);

  return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255), Math.round(alpha * 255)];
}

export function ContrastViewer({ imageUrl, heatmap, embedded = false }: ContrastViewerProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const hasImage = Boolean(imageUrl);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    if (!imageUrl) {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      return;
    }

    const img = new Image();
    img.onload = () => {
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;

      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

      if (!heatmap || heatmap.values.length !== heatmap.width * heatmap.height) {
        return;
      }

      const overlayCanvas = document.createElement('canvas');
      overlayCanvas.width = heatmap.width;
      overlayCanvas.height = heatmap.height;
      const overlayCtx = overlayCanvas.getContext('2d');
      if (!overlayCtx) return;

      const imageData = overlayCtx.createImageData(heatmap.width, heatmap.height);

      for (let i = 0; i < heatmap.values.length; i++) {
        const [r, g, b, a] = heatToRgba(heatmap.values[i] ?? 0);
        const px = i * 4;
        imageData.data[px] = r;
        imageData.data[px + 1] = g;
        imageData.data[px + 2] = b;
        imageData.data[px + 3] = a;
      }

      overlayCtx.putImageData(imageData, 0, 0);
      ctx.imageSmoothingEnabled = true;
      ctx.drawImage(overlayCanvas, 0, 0, canvas.width, canvas.height);
    };

    img.src = imageUrl;
  }, [imageUrl, heatmap]);

  const isOcclusion = heatmap?.method === 'occlusion_sensitivity';
  const ariaLabel = isOcclusion
    ? 'X-ray scan with model-based occlusion sensitivity heatmap'
    : 'X-ray scan with synthetic contrast overlay';

  const canvasBlock = (
    <div
      style={{
        position: 'relative',
        display: 'flex',
        minHeight: '200px',
        width: '100%',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        borderRadius: 'var(--radius-md)',
        background: 'rgba(2, 6, 23, 0.8)',
      }}
    >
      {hasImage ? (
        <canvas
          ref={canvasRef}
          style={{ maxHeight: 'min(70vh, 520px)', width: 'auto', maxWidth: '100%', objectFit: 'contain' }}
          aria-label={ariaLabel}
        />
      ) : (
        <div
          style={{
            display: 'flex',
            height: '100%',
            minHeight: '200px',
            width: '100%',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '0 var(--sp-4)',
            textAlign: 'center',
            fontSize: '14px',
            color: 'var(--text-secondary)',
            fontFamily: 'var(--font-mono)',
          }}
        >
          Upload and run analysis to render the scan.
        </div>
      )}
    </div>
  );

  const footnote = (
    <p
      style={{
        marginTop: 'var(--sp-2)',
        fontSize: '12px',
        fontStyle: 'italic',
        color: 'var(--text-secondary)',
        fontFamily: 'var(--font-mono)',
      }}
    >
      {isOcclusion
        ? 'ℹ This heatmap is generated by occlusion sensitivity. It estimates which image regions affected the model confidence by masking patches and re-running inference. Not a diagnostic feature.'
        : 'ℹ This overlay is derived from image contrast, not model gradients. It is a visual aid only and does not represent model-derived spatial explanations. Not a diagnostic feature.'}
    </p>
  );

  if (embedded) {
    return (
      <div style={{ display: 'flex', height: '100%', minHeight: 0, flexDirection: 'column' }}>
        {canvasBlock}
        {footnote}
      </div>
    );
  }

  return (
    <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-3)' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <h3 style={{ fontSize: '1.125rem', fontWeight: 600, color: 'var(--text-primary)' }}>
          {isOcclusion ? 'Model-based occlusion heatmap' : 'Visual contrast overlay (synthetic)'}
        </h3>
        <span style={{ fontSize: '12px', color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)' }}>
          {isOcclusion ? 'Model explanation' : 'Contrast-based overlay'}
        </span>
      </div>
      {canvasBlock}
      {footnote}
    </div>
  );
}
